/* UI uses real form controls. Responses are never placed in URLs or sent over a network. */
(function(P){
 'use strict';
 const $=id=>document.getElementById(id);
 const el=(tag,props={},text)=>{const n=document.createElement(tag);for(const [k,v] of Object.entries(props)){if(k==='class')n.className=v;else if(k.startsWith('on'))n.addEventListener(k.slice(2),v);else n.setAttribute(k,v);}if(text!==undefined)n.textContent=text;return n;};
 let state=null, chosenGrade=null, savePaused=false, observer=null, toastTimer;
 const announce=msg=>{clearTimeout(toastTimer);$('status').textContent=msg;toastTimer=setTimeout(()=>$('status').textContent='',6500);};
 function ask(title,message,choices){return new Promise(resolve=>{const d=$('confirm-dialog');$('dialog-title').textContent=title;$('dialog-message').textContent=message;$('dialog-actions').replaceChildren();let settled=false;const done=v=>{if(settled)return;settled=true;d.close();resolve(v);};for(const [value,label,primary] of choices){$('dialog-actions').append(el('button',{type:'button',class:primary?'primary':'',onclick:()=>done(value)},label));}d.oncancel=()=>done('cancel');d.showModal();});}
 function scrollToSection(id){const target=$(id==='review'?'section-review':'section-'+id);if(!target)return;if(id==='review')renderReview();target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});target.querySelector('h2').focus({preventScroll:true});markSection(id);}
 function markSection(id){const sec=P.common.sections.find(s=>s.id===id),stage=sec?.stage||'Review';$('section-position').textContent=sec?sec.id+' · '+sec.title:'Review & download';document.querySelectorAll('[data-section]').forEach(b=>b.setAttribute('aria-current',b.dataset.section===id?'step':'false'));document.querySelectorAll('[data-stage]').forEach(b=>b.setAttribute('aria-current',b.dataset.stage===stage?'step':'false'));}
 function progress(){if(!state)return;let total=0,done=0;for(const q of P.questions[state.grade].filter(q=>q.required&&P.isVisible(q,state.answers))){if(q.type==='matrix'){total+=q.minRows;done+=Math.min(q.minRows,Object.keys(state.answers[q.id]||{}).length);}else{total++;if(!P.answerError(q,state.answers))done++;}}const pct=Math.round(100*done/total);$('progress').value=pct;$('progress').textContent=pct+'%';$('progress-text').textContent=pct+'% of required answers · '+done+'/'+total;for(const s of P.common.sections){const complete=P.questions[state.grade].filter(q=>q.section===s.id&&q.required).every(q=>!P.answerError(q,state.answers));const badge=$('nav-done-'+s.id);if(badge)badge.textContent=complete?'✓':'';}}
 function save(){if(!state)return;if(savePaused){$('save-state').textContent='Saved copy cleared. Answers are still open in this tab; use a draft file if you need them.';return;}const r=P.storage.save(state);if($('save-state').textContent!==r.message)$('save-state').textContent=r.message;}
 function changed(q){$('finish').hidden=true;const wrap=$('q-'+q.id);if(wrap){wrap.classList.remove('invalid');const e=$('error-'+q.id);if(e)e.textContent='';}if(q.id==='interests'){
   const follow=P.questions[state.grade].find(x=>x.id==='interest-focus');const allowed=P.visibleOptions(follow,state.answers).map(o=>o.value);state.answers[follow.id]=(state.answers[follow.id]||[]).filter(x=>allowed.includes(x));if(!P.isVisible(follow,state.answers))delete state.answers[follow.id];$('q-interest-focus').replaceWith(renderQuestion(follow));
 }progress();renderReview();save();}
 function renderQuestion(q){const box=el('fieldset',{class:'question'+(q.id==='environments'?' environment':''),id:'q-'+q.id});if(!P.isVisible(q,state.answers))box.hidden=true;const legend=el('legend',{},q.prompt);legend.append(el('span',{class:'required'},q.required?(q.matrix==='skills'?'Required · choose one per skill':'Required · “not sure” is allowed'):'Optional'));box.append(legend,el('p',{class:'question-hint',id:'hint-'+q.id},q.hint));
  if(q.type==='multi'){
   const grid=el('div',{class:'choice-grid'});for(const o of P.visibleOptions(q,state.answers)){
    const input=el('input',{type:'checkbox',id:q.id+'--'+o.value,name:q.id,value:o.value,'aria-describedby':'hint-'+q.id+' error-'+q.id});input.checked=(state.answers[q.id]||[]).includes(o.value);
    input.addEventListener('change',()=>{let vals=[...(state.answers[q.id]||[])];if(input.checked){if(o.exclusive)vals=[o.value];else{vals=vals.filter(v=>!q.options.find(x=>x.value===v)?.exclusive);if(vals.length>=q.max){input.checked=false;$('error-'+q.id).textContent='Choose up to '+q.max+'. Uncheck one to choose something else.';announce('You can choose up to '+q.max+'.');return;}vals.push(o.value);}}else vals=vals.filter(v=>v!==o.value);state.answers[q.id]=vals;grid.querySelectorAll('input').forEach(i=>i.checked=vals.includes(i.value));changed(q);});
    const lab=el('label',{class:'choice',for:input.id});lab.append(input,el('span',{},o.label));grid.append(lab);
   }box.append(grid);
  }else if(q.type==='text'){
   const input=el('textarea',{id:'input-'+q.id,maxlength:String(P.config.maxResponseLength),'aria-label':q.prompt,'aria-describedby':'hint-'+q.id+' count-'+q.id+' error-'+q.id,autocomplete:'off',spellcheck:'true'});input.value=state.answers[q.id]||'';
   const foot=el('div',{class:'text-footer'}),counter=el('span',{class:'counter',id:'count-'+q.id},input.value.length+'/'+P.config.maxResponseLength);const unsure=el('button',{type:'button',class:'text-button',onclick:()=>{input.value='I don’t know yet.';state.answers[q.id]=input.value;counter.textContent=input.value.length+'/'+P.config.maxResponseLength;changed(q);input.focus();}},'Use “I don’t know yet”');input.addEventListener('input',()=>{state.answers[q.id]=input.value;counter.textContent=input.value.length+'/'+P.config.maxResponseLength;changed(q);});foot.append(unsure,counter);box.append(input,foot);
  }else{
   const list=el('div',{class:'rating-list'});for(const row of P.matrixRows(q)){
    const group=el('div',{class:'rating-row',role:'group','aria-labelledby':q.id+'-'+row.value+'-label'}),label=el('span',{class:'rating-label',id:q.id+'-'+row.value+'-label'},row.label),choices=el('div',{class:'rating-choices'});
    for(const level of P.matrixLevels(q)){
     const id=q.id+'--'+row.value+'--'+level.value,input=el('input',{type:'radio',id,name:q.id+'--'+row.value,value:level.value,'aria-label':row.label+' — '+level.label,'aria-describedby':'hint-'+q.id+' error-'+q.id});input.checked=(state.answers[q.id]||{})[row.value]===level.value;input.addEventListener('change',()=>{state.answers[q.id]||={};state.answers[q.id][row.value]=level.value;changed(q);});const lab=el('label',{class:'rating-choice',for:id});lab.append(input,el('span',{},level.label));choices.append(lab);
    }group.append(label,choices);list.append(group);
   }box.append(list);
  }box.append(el('p',{id:'error-'+q.id,class:'error',role:'alert'}));return box;
 }
 function showErrors(errors){document.querySelectorAll('.invalid').forEach(n=>n.classList.remove('invalid'));for(const e of errors){const box=$('q-'+e.id);if(box){box.classList.add('invalid');$('error-'+e.id).textContent=e.message;}}}

 function reviewAnswer(q){
   if(q.type!=='matrix')return P.exporter.labelAnswer(q,state.answers);
   const ratings=state.answers[q.id]||{},rows=P.matrixRows(q),groups=[];
   for(const level of P.matrixLevels(q)){const labels=rows.filter(r=>ratings[r.value]===level.value).map(r=>r.label);if(labels.length)groups.push(level.label+': '+labels.join('; '));}
   const unrated=rows.filter(r=>!ratings[r.value]).length;if(unrated)groups.push('Not rated: '+unrated+' of '+rows.length);
   return groups.join('\n');
 }
 function renderReview(){if(!state)return;const section=$('section-review');if(!section)return;section.replaceChildren(el('p',{class:'section-kicker'},'REVIEW → DOWNLOAD → TURN IN'),el('h2',{tabindex:'-1'},'Your answers, ready to check.'),el('p',{},'Your answers will help your teacher discover science connections and project ideas you may not have considered yet.'));
  section.append(el('h3',{},'Step 1 · Check your ID'),el('div',{class:'review-id'},state.classOnlyId),el('p',{class:'hint'},P.config.grades[state.grade]+(state.period?' · Period '+state.period:'')));
  const idcheck=el('input',{type:'checkbox',id:'confirm-id'}),idlabel=el('label',{class:'choice',for:'confirm-id'});idlabel.append(idcheck,el('span',{},'I checked every character against the ID my teacher gave me.'));section.append(idlabel,el('h3',{},'Step 2 · Review your answers'));
  const errors=P.validate(state),summary=el('div',{class:'review-status'});summary.append(el('strong',{},errors.length?errors.length+' question group'+(errors.length===1?' needs':'s need')+' attention.':'All required answers are complete.'));if(errors.length){const list=el('ul',{class:'error-list'});for(const err of errors){const q=P.questions[state.grade].find(x=>x.id===err.id),b=el('button',{type:'button',class:'text-button',onclick:()=>{if(!q){returnToStart();return;}showErrors(errors);scrollToSection(q.section);const control=$('q-'+q.id)?.querySelector('input,textarea');control?.focus({preventScroll:true});$('q-'+q.id)?.scrollIntoView({block:'start',behavior:'auto'});}},(q?q.prompt:'Class information')+' '+err.message);const li=el('li');li.append(b);list.append(li);}summary.append(list);}section.append(summary);
  const flags=P.piiFlags(state);if(flags.length){const alert=el('div',{class:'privacy-note'});alert.append(el('strong',{},'Check your written answers for personal details.'));flags.forEach(f=>alert.append(el('p',{},P.questions[state.grade].find(q=>q.id===f.questionId).prompt+' '+f.message)));section.append(alert);}
  for(const sec of P.common.sections){const block=el('div',{class:'review-block'}),h=el('h3',{},sec.id+' · '+sec.title);h.append(el('button',{type:'button',class:'text-button',onclick:()=>scrollToSection(sec.id)},'Edit '+sec.id));block.append(h);const dl=el('dl');for(const q of P.questions[state.grade].filter(q=>q.section===sec.id&&P.isVisible(q,state.answers))){dl.append(el('dt',{},q.prompt),el('dd',{},reviewAnswer(q)));}block.append(dl);section.append(block);}
  section.append(el('h3',{},'Step 3 · Create your submission file'),el('p',{},'Read your answers above. Remove names, contact details, account names, and private information about anyone.'));
  const privacy=el('input',{type:'checkbox',id:'confirm-review'}),pl=el('label',{class:'choice',for:'confirm-review'});pl.append(privacy,el('span',{},'I reviewed my answers and removed personal details.'));section.append(pl);
  const actions=el('div',{class:'actions'}),download=el('button',{type:'button',id:'download-final',class:'primary',onclick:()=>finalDownload('txt')},'Create submission file (.txt)'),json=el('button',{type:'button',id:'download-json',onclick:()=>finalDownload('json')},'Optional structured copy (.json)');download.disabled=json.disabled=true;const update=()=>{download.disabled=json.disabled=errors.length>0||!idcheck.checked||!privacy.checked;};idcheck.addEventListener('change',update);privacy.addEventListener('change',update);actions.append(download,json);section.append(el('p',{class:'hint'},'Complete required answers and check both boxes to enable download. You will attach the .txt file in Google Classroom.'),actions,el('button',{type:'button',class:'text-button',onclick:saveDraft},'Not finished? Save a draft instead'));
 }
 function finalDownload(kind){
  if(!state||!$('confirm-id')?.checked||!$('confirm-review')?.checked){announce('Check your ID and review your answers first.');return;}
  try{const errors=P.validate(state);if(errors.length){renderReview();showErrors(errors);announce('Complete the highlighted questions first.');return;}const text=kind==='txt'?P.exporter.txt(state):JSON.stringify(P.exporter.submission(state),null,2),name=P.exporter.filename(state,kind);P.exporter.download(text,name,kind==='txt'?'text/plain':'application/json');if(kind==='txt')showFinish(name);else announce('Optional JSON download requested. Use the .txt file for Classroom.');}catch(e){announce('The file could not be created. '+e.message);}
 }
 function showFinish(name){const f=$('finish');f.replaceChildren(el('p',{class:'eyebrow'},'LAST STEP · GOOGLE CLASSROOM'),el('h2',{id:'finish-title'},'Your file is ready. Now turn it in.'),el('p',{},'A download was requested. Check your Downloads folder before leaving this page. This website cannot tell whether the file saved or whether you turned it in.'),el('p',{class:'filename'},name));
 const ol=el('ol');['Make sure the file is in Downloads. Open it if you want to check it.','Return to the Google Classroom assignment.','Under Your work, choose Add or create → File. Use Upload / Browse to choose the file from Downloads.','Check that the attached file is '+name+'.','Click Turn in, confirm, and check that Classroom says Turned in.'].forEach(t=>ol.append(el('li',{},t)));f.append(ol);
 const checks=el('div',{class:'checklist'});['I found my downloaded file.','I attached the correct file.','The Class-Only ID in the filename matches my ID.','I clicked Turn in and checked its status.'].forEach((t,i)=>{const l=el('label',{for:'finish-check-'+i}),c=el('input',{type:'checkbox',id:'finish-check-'+i});l.append(c,el('span',{},t));checks.append(l);});f.append(checks);
 const actions=el('div',{class:'actions'});actions.append(el('button',{type:'button',onclick:()=>{if(!state){announce('Your answers were cleared. Use the file already in Downloads.');return;}P.exporter.download(P.exporter.txt(state),name,'text/plain');announce('Another download was requested. Your browser may add (1) to the filename. Use your latest complete copy.');}},'Download .txt again'),el('button',{type:'button',onclick:()=>{if(state)scrollToSection('review');}},'Back to review'),el('button',{type:'button',id:'finish-clear',class:'primary',onclick:async()=>{if(!$('finish-check-0').checked){announce('First check that your file is in Downloads.');return;}const choice=await ask('Clear the saved copy?','Your downloaded files and Classroom attachments will remain. Answers in this page and this ID’s browser save will be removed.',[['clear','Clear saved copy and finish',true],['cancel','Keep it for now']]);if(choice!=='clear')return;const r=P.storage.remove(state.classOnlyId);if(!r.ok){announce(r.message);return;}state=null;savePaused=true;$('workspace').hidden=true;$('questionnaire').replaceChildren();f.replaceChildren(el('h2',{id:'finish-title'},'Saved copy cleared.'),el('p',{},'Your downloaded file is still in Downloads. Make sure you attached it in Classroom and clicked Turn in.'),el('button',{onclick:returnToStart},'Return to the opening screen'));announce('Answers cleared from this page and this ID’s saved copy.');}},'Clear saved copy after checking my file'));f.append(actions,el('p',{class:'hint'},'On a shared Chromebook, clear the saved copy after you verify the download. Clearing browser answers does not delete downloaded files.'));f.hidden=false;f.scrollIntoView({behavior:'auto',block:'start'});f.focus();}
 function saveDraft(){if(!state)return;P.exporter.download(JSON.stringify(P.exporter.draft(state),null,2),P.exporter.filename(state,'draft'),'application/json');announce('Draft download requested. Keep the _DRAFT.json file to reopen later. It is not your final submission.');}
 function begin(s){state=s;savePaused=false;$('welcome').hidden=true;$('finish').hidden=true;$('workspace').hidden=false;$('identity-badge').textContent='G'+state.grade+' · '+state.classOnlyId+(state.period?' · Period '+state.period:'');$('questionnaire').replaceChildren();$('section-nav').replaceChildren();$('milestones').replaceChildren();
  P.common.sections.forEach((sec,i)=>{const section=el('section',{class:'section',id:'section-'+sec.id,'aria-labelledby':'heading-'+sec.id}),kick=el('p',{class:'section-kicker'});kick.append(el('span',{},sec.id),document.createTextNode(sec.stage.toUpperCase()));section.append(kick,el('h2',{id:'heading-'+sec.id,tabindex:'-1'},sec.title),el('p',{class:'section-intro'},sec.intro));P.questions[state.grade].filter(q=>q.section===sec.id).forEach(q=>section.append(renderQuestion(q)));const nav=el('div',{class:'nav-actions'});nav.append(el('button',{type:'button',onclick:()=>i?scrollToSection(P.common.sections[i-1].id):window.scrollTo({top:0,behavior:'auto'})},'Previous'),el('button',{type:'button',class:'primary',onclick:()=>scrollToSection(i===P.common.sections.length-1?'review':P.common.sections[i+1].id)},i===P.common.sections.length-1?'Review answers':'Next'));section.append(nav);$('questionnaire').append(section);const b=el('button',{type:'button','data-section':sec.id,onclick:()=>scrollToSection(sec.id)},sec.id+' · '+sec.title);b.append(el('span',{id:'nav-done-'+sec.id,class:'done','aria-hidden':'true'}));$('section-nav').append(b);});
  $('questionnaire').append(el('section',{class:'section',id:'section-review','aria-label':'Review your answers'}));$('section-nav').append(el('button',{type:'button','data-section':'review',onclick:()=>scrollToSection('review')},'Review & download'));
  [['Discover','A'],['Explore','B'],['Investigate','E'],['Consult','K'],['Review','review']].forEach(([stage,id],i)=>$('milestones').append(el('button',{type:'button','data-stage':stage,onclick:()=>scrollToSection(id)},(i+1)+' '+stage.toUpperCase())));
  renderReview();progress();save();observer?.disconnect();observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)markSection(e.target.id.replace('section-',''));},{rootMargin:'-140px 0px -55% 0px',threshold:0});document.querySelectorAll('.section').forEach(n=>observer.observe(n));scrollToSection('A');
 }
 function returnToStart(){observer?.disconnect();state=null;$('workspace').hidden=true;$('finish').hidden=true;$('welcome').hidden=false;$('questionnaire').replaceChildren();$('class-id').value='';$('period').value='';$('start-error').textContent='';window.scrollTo({top:0,behavior:'auto'});$('class-id').focus();}
 Object.entries(P.config.grades).forEach(([grade,label])=>{const b=el('button',{type:'button','data-grade':grade,'aria-pressed':'false',onclick:()=>{chosenGrade=Number(grade);$('start-form').hidden=false;$('chosen-grade').textContent=label;document.querySelectorAll('[data-grade]').forEach(n=>n.setAttribute('aria-pressed',n.dataset.grade===grade?'true':'false'));$('class-id').focus();}},label);$('grade-buttons').append(b);});
 $('id-help').textContent=P.config.idHelp;$('period-wrap').hidden=!P.config.showPeriod;$('period').append(el('option',{value:''},'Choose your period'));P.config.periods.forEach(p=>$('period').append(el('option',{value:p},p)));$('version').textContent=P.config.questionnaireVersion;
 $('start-form').addEventListener('submit',async e=>{e.preventDefault();const id=$('class-id').value.trim().toUpperCase(),period=P.config.showPeriod?$('period').value:'';$('class-id').value=id;if(!chosenGrade||!P.idValid(id)){ $('start-error').textContent='Check your ID. '+P.config.idHelp;$('class-id').focus();return;}if(P.config.showPeriod&&P.config.periodRequired&&!period){$('start-error').textContent='Choose your class period.';$('period').focus();return;}const r=P.storage.load(id);if(r.state){if(r.state.grade!==chosenGrade){$('start-error').textContent='Saved answers for this ID belong to Grade '+r.state.grade+'. Choose that grade, or ask your teacher before clearing saved answers.';return;}const action=await ask('Saved answers found','Continue the saved questionnaire for '+id+'? Saved period: '+(r.state.period||'not used')+'. You selected period '+(period||'not used')+'.',['restore','new','cancel'].map(v=>v==='restore'?[v,'Restore my answers',true]:v==='new'?[v,'Start over for this ID']:[v,'Cancel']));if(action==='cancel')return;if(action==='restore'){begin({...r.state,period});return;}}
 if(!r.ok){const choice=await ask('Recovery is unavailable',r.message+' If you continue, save a draft file before leaving.',[['continue','Continue with new answers',true],['cancel','Cancel']]);if(choice!=='continue')return;}begin({grade:chosenGrade,classOnlyId:id,period,answers:{}});});
 $('change-class').addEventListener('click',async()=>{const action=await ask('Change ID or grade?','This closes the current questionnaire. A browser save may remain under the old ID. Download a draft first if you want a portable copy.',[['save','Save draft and change',true],['change','Change without downloading'],['cancel','Keep working']]);if(action==='cancel')return;if(action==='save')saveDraft();returnToStart();});
 $('save-draft').addEventListener('click',saveDraft);for(const id of ['open-draft','import-start'])$(id).addEventListener('click',()=>$('draft-input').click());
 $('draft-input').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>P.config.maxImportBytes)throw Error('This file is too large to be a questionnaire draft.');const s=P.cleanImport(JSON.parse(await file.text()));const answer=await ask('Open this draft?','Grade '+s.grade+' · ID '+s.classOnlyId+' · Period '+(s.period||'not used')+'. Check this is your ID. This replaces any answers currently open and the saved copy for this ID on this device.',[['open','This is my draft — open it',true],['cancel','Cancel']]);if(answer==='open'){chosenGrade=s.grade;begin(s);announce('Draft restored. Review your ID and continue.');}}catch(err){announce(err instanceof SyntaxError?'That file is not readable JSON. Choose the _DRAFT.json file.':err.message);}});
 $('clear-device').addEventListener('click',async()=>{const answer=await ask('Clear this device’s saved answers?','This removes saved answers for this questionnaire on this browser, including answers open now. Download a draft first if you need them. Downloaded files and Classroom attachments are not deleted.',[['clear','Clear saved answers',true],['cancel','Keep answers']]);if(answer!=='clear')return;const r=P.storage.clearAll();if(!r.ok){announce(r.message);return;}returnToStart();announce(r.message);});

 // Optional browser-native navigation adapter. It never exposes, changes, or exports answers.
 if(document.modelContext?.registerTool){
   const controller=new AbortController();
   try{Promise.resolve(document.modelContext.registerTool({
     name:'navigate_discovery_section',title:'Go to a questionnaire section',
     description:'Navigate within an already open questionnaire. Does not read, change, save, or export responses.',
     inputSchema:{type:'object',properties:{section:{type:'string',enum:[...P.common.sections.map(s=>s.id),'review']}},required:['section'],additionalProperties:false},
     annotations:{readOnlyHint:false,untrustedContentHint:false},
     execute(input){if(!state)throw Error('Open a questionnaire first.');if(!input||Object.keys(input).length!==1||![...P.common.sections.map(s=>s.id),'review'].includes(input.section))throw Error('Choose a valid section.');scrollToSection(input.section);return {section:input.section,navigated:true};}
   },{signal:controller.signal})).catch(()=>{});}catch(e){/* Unsupported adapters do not affect the questionnaire. */}
   window.addEventListener('pagehide',()=>controller.abort(),{once:true});
 }
 // Autosave is synchronous after each edit, so a refresh can recover even if it interrupts typing.
 // No beforeunload blocker: students may close safely when the saved indicator is present.
})(PD);
